baseURL = 'https://grimreaper.github.io/arbitration/'
languageCode = 'en-us'
title = 'Arbitration Information'

theme = "hugo-book"

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

# https://themes.gohugo.io/themes/hugo-book/

[params]
  BookRepo = 'https://github.com/grimreaper/arbitration'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/master'
[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 1
